id = "css-class-autocomplete"
name = "CSS Class Autocomplete"
version = "0.1.0"
schema_version = 1
authors = ["Cesar Eug√©nio"]
description = "Autocompletes CSS class names in HTML and PHP files"
repository = "https://github.com/c-eugenio/css-autocomplete-zed"
themes = []
icon_themes = []
languages = []
capabilities = []

[lib]
kind = "Rust"
version = "0.7.0"

[language_servers.css-class-lsp]
languages = ["HTML", "PHP"]

[language_servers.css-class-lsp.language_ids]
HTML = "html"
PHP = "php"
